import { StandardTestCard } from '../types';

export const OFFICIAL_SANDBOX_CARDS: StandardTestCard[] = [
  {
    id: 'stripe-success-visa',
    title: 'Visa Sandbox - Aprovação Direta',
    category: 'Sucesso',
    cardNumber: '4242 4242 4242 4242',
    brand: 'visa',
    expDate: '12/28',
    cvv: '123',
    expectedOutcome: 'Aprovado (HTTP 200 - Code 00)',
    responseCode: '00',
    description: 'Cartão de teste oficial para simulação de fluxo com autorização imediata e sem atrito.',
  },
  {
    id: 'mastercard-success',
    title: 'Mastercard Sandbox - Sucesso',
    category: 'Sucesso',
    cardNumber: '5555 5555 5555 4444',
    brand: 'mastercard',
    expDate: '10/29',
    cvv: '789',
    expectedOutcome: 'Aprovado (HTTP 200 - Code 00)',
    responseCode: '00',
    description: 'Padrão Mastercard internacional para testes de transações aprovadas em sandbox.',
  },
  {
    id: 'amex-success',
    title: 'American Express - Sucesso',
    category: 'Sucesso',
    cardNumber: '3782 822463 10005',
    brand: 'amex',
    expDate: '08/27',
    cvv: '1234',
    expectedOutcome: 'Aprovado (HTTP 200 - Code 00)',
    responseCode: '00',
    description: 'Cartão Amex padrão de 15 dígitos com 4 dígitos no código de segurança CID/CVV.',
  },
  {
    id: 'elo-success-br',
    title: 'Elo Nacional - Sucesso (Brasil)',
    category: 'Sucesso',
    cardNumber: '5067 7820 0000 0005',
    brand: 'elo',
    expDate: '11/30',
    cvv: '999',
    expectedOutcome: 'Aprovado (HTTP 200 - Code 00)',
    responseCode: '00',
    description: 'BIN Elo de teste amplamente utilizado para validação de fluxos adquirentes locais como Cielo e Rede.',
  },
  {
    id: 'decline-insufficient-funds',
    title: 'Recusa - Saldo Insuficiente',
    category: 'Recusa',
    cardNumber: '4000 0000 0000 9995',
    brand: 'visa',
    expDate: '06/27',
    cvv: '123',
    expectedOutcome: 'Recusado: Saldo Insuficiente (Code 51)',
    responseCode: '51',
    description: 'Simula recusa do emissor por limite ou fundos não disponíveis na conta do titular.',
  },
  {
    id: 'decline-card-expired',
    title: 'Recusa - Cartão Expirado',
    category: 'Recusa',
    cardNumber: '4000 0000 0000 0069',
    brand: 'visa',
    expDate: '01/22',
    cvv: '456',
    expectedOutcome: 'Recusado: Cartão Expirado (Code 54)',
    responseCode: '54',
    description: 'Data de validade anterior à data atual do sistema para testar mensagens de erro de expiração no checkout.',
  },
  {
    id: 'decline-lost-stolen',
    title: 'Recusa - Cartão Bloqueado / Roubado',
    category: 'Recusa',
    cardNumber: '4000 0000 0000 0041',
    brand: 'visa',
    expDate: '09/28',
    cvv: '321',
    expectedOutcome: 'Recusado: Contatar Emissor / Bloqueado (Code 04/07)',
    responseCode: '04',
    description: 'Simula bloqueio por perda/furto ou restrição cadastral permanente junto ao banco emissor.',
  },
  {
    id: 'security-3ds-challenge',
    title: 'Autenticação 3D Secure 2.0 (Desafio)',
    category: 'Segurança',
    cardNumber: '4000 0002 0000 3220',
    brand: 'visa',
    expDate: '12/27',
    cvv: '777',
    expectedOutcome: 'Requer Autenticação (3DS Challenge / OTP)',
    responseCode: '3DS',
    description: 'Dispara fluxo de verificação em duas etapas via SMS/App bancário para cumprimento do SCA.',
  },
  {
    id: 'security-fraud-risk',
    title: 'Antifraude - Score de Risco Alto',
    category: 'Segurança',
    cardNumber: '4000 0000 0000 0082',
    brand: 'visa',
    expDate: '05/29',
    cvv: '888',
    expectedOutcome: 'Bloqueado por Antifraude (Risk Score > 90)',
    responseCode: '59',
    description: 'Testa integração com motores de risco (ex: ClearSale, Cybersource, Radar) e regras de cancelamento preventivo.',
  },
  {
    id: 'special-corporate-purchasing',
    title: 'Cartão Corporativo / B2B Level 3',
    category: 'Especiais',
    cardNumber: '5100 0000 0000 0000',
    brand: 'mastercard',
    expDate: '04/28',
    cvv: '456',
    expectedOutcome: 'Aprovado com Requisitos Level 3 Data',
    responseCode: '00-L3',
    description: 'Cartão corporativo empresarial exigindo informações adicionais de fatura e tributos na conciliação.',
  },
];
